defaults.url=https://sentry.io/
defaults.org=atillaproj
defaults.project=4507907274440784
cli.executable=../../../.npm/_npx/a8388072043b4cbc/node_modules/@sentry/cli/bin/sentry-cli
auth.token= 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